### ISSUE TITLE
一些格式优化

### ISSUE THREAD

**Issue by onlyice** [zheng-ji/goSnowFlake#4]
Go 我不懂，但是写一些细节的点。。

### 项目名不要用驼峰命名法

`go-snowflake` 更好。如果你看看 Go 的 [流行仓库][1]，很少会用驼峰命名法。单个单词、全小写是最佳的，其次是带短减号 `-` 的命名。也可以考虑跟流行的 Go 库使用类似的命名。

### 格式细节

可以参考 [LeanCloud 文案风格指南][2]，里面的建议都非常不错。

这次的排版比以前好太多了，但是 README 里还有一些小问题：

* 中英文混排的情况，中文间的内容建议用中文标点
* 第一句英文描述 "According to the Twitter SnowFlake Theory..."，这句不是标题，不能全部首字母大写，按正常的句子写就好；另外这句话的表达有点啰嗦，可以改成 "A threadsafe unique ID generator inspired by Twitter SnowFlake theory."，并不需要说是 Go 实现的（个人观点。。）

项目的描述文字也有类似的问题：

![image](https://cloud.githubusercontent.com/assets/1173899/13842325/81369c2e-ec68-11e5-853b-ca66f015b4f0.png)

### 内容

Description 一段的内容跟标题不符。里面只是说明了 ID 的结构，并不适合叫 Description。而且有一些英文表达的问题，比如：

* "Sequence is zero default" should be "by default".
* "when timestamp is the same"，首字母没大写
* 最后一句没有句号结尾。

总体看起来不够通顺，可能会影响人们判断你这个库的质量。

最好有个同步的中文文档，方便推广。

不知道 Go 有无生成 UUID 的标准库？或者其他已经流行的第三方库？可以考虑写个性能/功能对比，方便用户选择。

[1]: https://github.com/trending/go
[2]: http://open.leancloud.cn/copywriting-style-guide.html

**Comment by zheng-ji** [comment]
多谢建议：）
