### ISSUE TITLE
timeReGen算法有误

### ISSUE THREAD

**Issue by ligh0721** [zheng-ji/goSnowFlake#9]
当时间戳相同时，会消耗seq，当seq消耗殆尽后，需要在reGen里无限循环至生成新的时间戳，但是在timeReGen里，ts默认等于time.Now().UnixNano()，这个要比使用timeGen生成的数值大1000 * 1000倍，所以这个循环无论如何也会直接break

**Comment by bnfan** [comment]
有bug，会生成重复的id

**Comment by liuyongshuai** [comment]
我写了个各个域的位数可以调整的，https://github.com/liuyongshuai/tofuutils/blob/master/snowflake.go
timeReGen是不是应该这样写：
rawTs := time.Now().UnixNano()
ret := (rawTs >> 22) << 22
return ret

**Comment by liuyongshuai** [comment]
timeReGen是不是应该这样写：
rawTs := time.Now().UnixNano()
ret := (rawTs >> 22) << 22
return ret

**Comment by liuyongshuai** [comment]
感觉timeReGen应该这样写是不是好一些~~~
func (iw *IdWorker) timeReGen(last int64) int64 {
	for {
                ts := iw.timeGen()
		if ts > last {
			return ts
		} 
	}
}

**Comment by zheng-ji** [comment]
Thanks 已经Fix
